name: business_management_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning:  Keep your app version up-to-date for release and tracking changes.
version: 1.0.0+1 

# Flutter SDK Version:  
#  * Choose a range that's supported by your dependencies and meets your project's requirements. 
#  * Always use caret (`^`) for major versions to auto-update minor releases.
environment:
  sdk: '>=2.18.0 <3.0.0'  # Example: Adjust this based on your Flutter version 

# Dependencies:
#  * Carefully choose package versions and consider using caret (`^`) for automatic minor version upgrades.
#  * Make sure your choices are compatible with your Flutter SDK version.
dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.29.0 
  firebase_auth: ^4.19.1 
  cloud_firestore: ^4.16.1 
  firebase_storage: ^11.7.2
  firebase_app_check: ^0.2.2+5
  firebase_database: ^10.0.14  # or the latest compatible version

  # UI & Data Management
  provider: ^6.1.2  # State management
  charts_flutter: ^0.12.0  # Charts 
  cached_network_image: ^3.3.1  # Image caching
  google_fonts: ^4.0.3  # Google Fonts 
  carousel_slider: ^4.0.0 # Image carousel

  # Other
  change_app_package_name: ^1.1.0  # Package name management (if needed)
  google_sign_in: ^5.2.1  # Google Sign-In 
  font_awesome_flutter: ^10.7.0  # Font Awesome Icons
  fluttertoast: ^8.1.2  # Toasts
  file_picker: ^4.0.0  # File picking
  flutter_chatgpt_api: ^1.1.0  # ChatGPT API 
  url_launcher: ^6.1.10  # URL launching
  flutter_secure_storage: ^5.0.2  # Secure storage (for credentials) 
  cupertino_icons: ^1.0.2  # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2  # Linting for code quality

flutter:
  uses-material-design: true # Use Material Design (usually a good choice)

  # Asset Management: 
  #  * Add images, audio, etc. to the `assets` section.
  #  * Ensure your asset paths are correct and correspond to your app's structure.
  assets:
    - assets/business_manager.png
    - assets/logo.png

  # Fonts: Add any custom fonts you want to use in your app.
  #  * Replace the placeholders with your actual font file names.
  fonts:
    - family: MyFont  # Choose a name for your font 
      fonts:
        - asset: fonts/MyFont-Regular.ttf # Adjust the font file path
        - asset: fonts/MyFont-Bold.ttf  # Add bold or other styles if needed
